spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bar_control_test
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update

  application:
    name: barcontrol-server

  security:
    user:
      name: admin
      password: admin123

server:
  port: 9999
